Changed the `npm` command based on whether the user runs Windows
AdrieanKhisbe/bundle-phobia-cli pull request #37
Opened 2020-11-29 16:38 UTC by soimon

This pull requests addresses a bug I ran into on Windows 10.
Every audit of a package fails with the error `spawn npm ENOENT`.
This is due to (at least my) Windows requiring `npm.cmd` instead of `npm` to function.
This pr replaces the hardcoded `npm` with a conditional string based on the OS.

2020-12-03 06:22 UTC, AdrieanKhisbe requested changes
Thanks for your proposal @soimon 

I think it would be best not to rely on platform name,
and check `npm` if available, otherwise try that `npm.cmd` if available.
(If you have doc about `npm.cmd` on windows, it would be nice.)

Also, maybe node set an environment variable about npm executable name that could be used.

And last but not least, please include tests for your feature. :)

2020-12-03 06:22 UTC, AdrieanKhisbe commented on src/npm-utils.js
> +const getNpmCommand = () => (process.platform.startsWith('win') ? 'npm.cmd' : 'npm');
This should take `platform` as argument to be testable

2020-12-03 17:48 UTC, soimon commented
Thanks for your response @AdrieanKhisbe.
My apologies for the lack of tests: this is my first PR so it might be a bit rocky.
Let me first say that this is not an enhancement, but a fix: the package as it is now does not work at all on my Windows machine. The proposed `npm.cmd` is not a different package: it is the exact name (with file extension) of the one and only `npm` package. Therefore every Windows computer that has `npm` installed has `npm.cmd` installed.

I agree with you though that an OS check is a bit of an ugly solution to include in that particular file. Therefore I propose a different approach: by providing [`execFile`](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) with the option `{shell: true}`, the command is run (in the background) through the system shell. When fired like this `npm` resolves correctly on Windows and the command works perfectly fine without the need for conditionals or additional tests. Seeing that all the checks (on Linux) have passed as well I think it is safe to implement this fix and make the package function cross-platform.

2020-12-04 14:19 UTC, AdrieanKhisbe commented
Thanks @soimon,
if it's just adding the `shell` option flag to node `execFile`, there is no real need to add cross platform test indeed.

(I was cautious as was thinking this maybe was not a generalised problem on windows, and so wanted to ensure no regression would be introduce on that env)

and yes, that was definitely an issue introduced in #33 by removing `shelljs` :shell:

2020-12-04 14:19 UTC, AdrieanKhisbe approved these changes

2020-12-04 14:27 UTC, AdrieanKhisbe commented
@soimon, I was about to merge, but I thought to check if there was another place that would need the flag.
And indeed, there was one : https://github.com/AdrieanKhisbe/bundle-phobia-cli/blob/master/src/install.js#L114

Would you mind adding the `{shell: true}`? or allow me to push on your branch? 🙂 

thanks in advance :)

2020-12-04 17:14 UTC, soimon commented
Good one, I hadn't used that feature so I didn't run into the problem yet.
I pushed the final change, so if the checks complete then it's ready for launch 🚀
Thanks for your assistance 👍

2020-12-06 13:28 UTC, AdrieanKhisbe approved these changes

2020-12-06 13:29 UTC, merged

2020-12-06 13:47 UTC, AdrieanKhisbe commented
Released as `v0.14.11` [f37949a]

2020-12-06 13:47 UTC, AdrieanKhisbe commented
I just published it @soimon,
you can give a try and tell me if it works for you on windows 🙂

2020-12-06 23:29 UTC, soimon commented
The `bundle-phobia` command now works without a problem 😄
There is a problem with `bundle-phobia-install` though that seems unrelated to this change.
As I do not use that feature myself I will just file a new issue with the details.